#-------------------------#
#                         #
#   NAME:     ACUBELETS   #
#   AUTHOR:   DavidML16   #
#                         #
#-------------------------#


# Language of plugin
# Availables by default: EN, ES
Language: EN


# Database details
MySQL:
    Enabled: false
    Host: localhost
    Port: 3306
    User: root
    Password: example
    Database: acubelets


# Enable/disable if execute a command when click on barrier
# When dont have any cubelets to open
NoCubelets:
    ExecuteCommand: false
    Command: 'help'


# Enable/disable cubelet crafting
Crafting: true


# Enable/disable cubelet rewards preview with MIDDLE-CLICK
RewardsPreview: false