#-------------------------#
#                         #
#   NAME:     ACUBELETS   #
#   AUTHOR:   DavidML16   #
#                         #
#-------------------------#


# LANGUAGE OF THE PLUGIN
# AVAILABLES BY DEFAULT: EN, ES
Language: EN


# DATABASE DETAILS
MySQL:
    Enabled: false
    Host: localhost
    Port: 3306
    User: root
    Password: example
    Database: acubelets