#-------------------------#
#                         #
#   NAME:     ACUBELETS   #
#   AUTHOR:   DavidML16   #
#                         #
#-------------------------#


# Language of plugin
# Availables by default: EN, ES
Language: EN


# Command name, default: /cubelets and /points
# For the changes to take effect, a full server restart is required
Commands:
    Cubelets: cubelets
    Points: points


# Database details
MySQL:
    Enabled: false
    Host: localhost
    Port: 3306
    User: root
    Password: example
    Database: acubelets


# Enable/disable if execute a command when click on barrier
# When dont have any cubelets to open
NoCubelets:
    ExecuteCommand: false
    Command: 'help'


# Enable/disable cubelet crafting
Crafting: true


# Enable/disable cubelet rewards preview
# Available click types: LEFT, RIGHT, MIDDLE, SHIFT_LEFT or SHIFT_RIGHT
RewardsPreview:
    Enabled: false
    ClickType: SHIFT_LEFT


# Enable/disable reward duplication system
# Change the command to execute to the one of the plugin you are using
# Change the command to give duplicated points
RewardsDuplication:
    Enabled: false
    PermissionCommand: 'lp user %player% permission set %permission% true'
    PointsCommand: 'points give %player% %points%'


# Change hologram settings
# Update interval default: 30 (1.5s)
# Color animation default colors: &f and &c
# Duplication hologram visible to all players (Default: false)
Holograms:
    UpdateInterval: 30
    ColorAnimation:
        - '&f'
        - '&c'
    Duplication:
        VisibleToAllPlayers: false