name: ACubelets
version: ${project.version}
main: me.davidml16.acubelets.Main
depend: [HolographicDisplays, ProtocolLib]
softdepend: [PlaceholderAPI]
authors: [DavidML16]
api-version: 1.13
commands:
  cubelets:
    description: Use this to see all commands.