name: ACubelets
version: ${project.version}
main: me.davidml16.acubelets.Main
depend: [HolographicDisplays, ProtocolLib]
softdepend: [PlaceholderAPI, Vault, Multiverse-Core, Hyperverse]
authors: [DavidML16]
api-version: 1.13